#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

echo "[!] Make sure you are using OpenFOAM 2.0.1 (run OF201) [!]"

# Create the base mesh
echo "Creating the base mesh..."
runApplication blockMesh

# Create the patch for the inlet (face "bubble")
echo "Creating the patch for the inlet..."
setSet -batch makeFaceSet.setSet > log.setSet_1
createPatch -overwrite > log.createPatch

# Refine the mesh around the inlet
echo "Refining the mesh..."
setSet -batch refine.setSet > log.setSet_2
refineMesh -dict -overwrite > log.refineMesh_1

# Initilize a part of the column with alpha=0
echo "Initializing alpha..."
runApplication setFields

# Start the solver
echo "Running the case..."
runApplication $application
